# =============================================================================
# AWS CodeBuild Buildspec for ExpertelIQ2 Scraper
# =============================================================================
# Triggered by GitHub push → Deploys to EC2 via SSM
# =============================================================================

version: 0.2

env:
  variables:
    APP_DIR: "/opt/experteliq2-scraper"

phases:
  pre_build:
    commands:
      - echo "=========================================="
      - echo "ExpertelIQ2 Scraper - CI/CD Pipeline"
      - echo "Environment $ENVIRONMENT"
      - echo "Instance ID $INSTANCE_ID"
      - echo "=========================================="
      - echo "Pre-build started at $(date)"

  build:
    commands:
      - echo "Build started at $(date)"
      - echo "Deploying to EC2 instance $INSTANCE_ID..."
      - |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters '{"commands":["sudo -u scraper git config --global --add safe.directory /opt/experteliq2-scraper","cd /opt/experteliq2-scraper","sudo -u scraper git fetch origin","sudo -u scraper git reset --hard origin/'"$CODEBUILD_SOURCE_VERSION"'","sudo -u scraper /home/scraper/.local/bin/poetry install --no-root","sudo systemctl restart scraper.timer","echo Deployment completed"]}' \
          --timeout-seconds 300 \
          --region "$AWS_DEFAULT_REGION" \
          --query 'Command.CommandId' \
          --output text)
        echo "SSM Command ID: $COMMAND_ID"
      - |
        for i in $(seq 1 30); do
          STATUS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --query 'Status' \
            --output text \
            --region "$AWS_DEFAULT_REGION" 2>/dev/null || echo "Pending")
          echo "Command status: $STATUS"
          if [ "$STATUS" = "Success" ]; then
            echo "Deployment successful!"
            exit 0
          elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
            echo "Deployment failed with status: $STATUS"
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --region "$AWS_DEFAULT_REGION"
            exit 1
          fi
          sleep 10
        done

  post_build:
    commands:
      - echo "Post-build completed at $(date)"

cache:
  paths:
    - '/root/.cache/pip/**/*'
