# =============================================================================
# AWS CodeBuild Buildspec for ExpertelIQ2 Scraper
# =============================================================================
# Triggered by GitHub push → Deploys to EC2 via SSM
# =============================================================================

version: 0.2

env:
  variables:
    APP_DIR: "/opt/experteliq2-scraper"

phases:
  pre_build:
    commands:
      - echo "=========================================="
      - echo "ExpertelIQ2 Scraper - CI/CD Pipeline"
      - echo "Environment $ENVIRONMENT"
      - echo "Branch $GITHUB_BRANCH"
      - echo "Instance ID $INSTANCE_ID"
      - echo "Source Version $CODEBUILD_SOURCE_VERSION"
      - echo "=========================================="
      - echo "Pre-build started at $(date)"

  build:
    commands:
      - echo "Build started at $(date)"
      - echo "Deploying to EC2 instance $INSTANCE_ID..."
      - |
        # Build the deployment script as a single command to ensure proper execution context
        DEPLOY_SCRIPT="set -e && \
          cd $APP_DIR && \
          git config --global --add safe.directory $APP_DIR && \
          sudo -u scraper git config --global --add safe.directory $APP_DIR && \
          echo 'Current directory:' && pwd && \
          echo 'Current commit:' && git rev-parse HEAD && \
          sudo -u scraper git fetch origin $GITHUB_BRANCH && \
          sudo -u scraper git reset --hard origin/$GITHUB_BRANCH && \
          echo 'New commit:' && git rev-parse HEAD && \
          sudo -u scraper /home/scraper/.local/bin/poetry install --no-root && \
          sudo systemctl restart scraper.timer && \
          echo 'Deployment completed successfully'"

        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters "{\"commands\":[\"$DEPLOY_SCRIPT\"]}" \
          --timeout-seconds 300 \
          --region "$AWS_DEFAULT_REGION" \
          --query 'Command.CommandId' \
          --output text)
        echo "SSM Command ID: $COMMAND_ID"
      - |
        # Wait for SSM command to complete and show output
        for i in $(seq 1 30); do
          STATUS=$(aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID" \
            --region "$AWS_DEFAULT_REGION" \
            --query 'Status' \
            --output text 2>/dev/null || echo "Pending")

          echo "Command status: $STATUS"

          if [ "$STATUS" = "Success" ]; then
            echo "=========================================="
            echo "Deployment Output:"
            echo "=========================================="
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --region "$AWS_DEFAULT_REGION" \
              --query 'StandardOutputContent' \
              --output text
            echo "=========================================="
            echo "Deployment successful!"
            exit 0
          elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ] || [ "$STATUS" = "TimedOut" ]; then
            echo "Deployment failed with status: $STATUS"
            echo "=========================================="
            echo "Error Output:"
            echo "=========================================="
            aws ssm get-command-invocation \
              --command-id "$COMMAND_ID" \
              --instance-id "$INSTANCE_ID" \
              --region "$AWS_DEFAULT_REGION" \
              --query '[StandardOutputContent, StandardErrorContent]' \
              --output text
            exit 1
          fi
          sleep 10
        done
        echo "Timeout waiting for deployment"
        exit 1

  post_build:
    commands:
      - echo "Post-build completed at $(date)"

cache:
  paths:
    - '/root/.cache/pip/**/*'
